name: Container Image Vulnerability Scan
description: Scans Container Images For Vulnerabilities
inputs:
  image-ref:
    description: The image reference to scan for vulnerabilities
    required: true
outputs:
  results:
    description: Container image vulnerability scan results
    value: ${{ steps.results.outputs.markdown }}
runs:
  using: composite
  steps:
    - name: Run Trivy
      continue-on-error: true
      run: |
        trivy image \
          --format table \
          --vuln-type os,library \
          --severity CRITICAL,HIGH \
          --output trivy-results \
          ${{ inputs.image-ref }} || true
      shell: bash
    - name: Read Trivy Results
      id: results
      run: |
        if [ -s trivy-results ]; then
          echo 'markdown<<EOF' >> $GITHUB_OUTPUT
          echo ':bangbang: ' >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          cat trivy-results >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        else
          echo 'markdown=:heavy_check_mark:' >> $GITHUB_OUTPUT
        fi
      shell: bash
