name: Build and push apps
description: Build and push apps
inputs:
  github-token:
    description: The GitHub token used for accessing internal repositories
    required: true
  manifest-file:
    description: The manifest file (e.g. backendapp.yaml or generatorapp.yaml)
    required: true
  default-app-dockerfile:
    required: true
    description: The path to the default app Dockerfile
  build-apps-output-file:
    description: Build apps output file
    required: true
  image-repository:
    description: The docker repository you are about to push the docker images to
    required: true
  image-version:
    description: The version of the docker images
    required: true
runs:
  using: composite
  steps:
    - name: Build and push apps
      run: operator-build-push-apps.sh ${{ inputs.default-app-dockerfile }} ${{ inputs.manifest-file }} ${{ inputs.build-apps-output-file }} ${{ inputs.image-repository }} ${{ inputs.image-version }} ${{ inputs.github-token }}
      shell: bash
