name: Security Review Comment
description: Security Review Comment
inputs:
  pull-request-number:
    description: The number of the pull request
    required: true
  golang-security-scan:
    description: Golang security scan results in markdown
    required: true
  docker-vulnerability-scan:
    description:  Container image vulnerability scan results
    required: true
  github-token:
    description: The GitHub token used for accessing internal repositories
    required: true
runs:
  using: composite
  steps:
    - name: Find Security Review Comment
      # peter-evans/find-comment@v2.1.0
      uses: peter-evans/find-comment@f4499a714d59013c74a08789b48abe4b704364a0
      id: find-comment
      with:
        issue-number: ${{ inputs.pull-request-number }}
        comment-author: 'github-actions[bot]'
        body-includes: 'Security Review'
    - name: Add Security Review Comment
      # peter-evans/create-or-update-comment@v2.1.0
      uses: peter-evans/create-or-update-comment@5adcb0bb0f9fb3f95ef05400558bdb3f329ee808
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ inputs.pull-request-number }}
        body: |
          ## Security Review
          ### GoLang: ${{ inputs.golang-security-scan }}
          ### Container Image: ${{ inputs.docker-vulnerability-scan }}
        edit-mode: replace
        token: ${{ inputs.github-token }}
