name: Test Reporter
description: Shows test results in GitHub UI
inputs:
  test-results-directory:
    description: The test results output directory
    required: true
  github-token:
    description: The GitHub token used for accessing internal repositories
    required: true
runs:
  using: composite
  steps:
    - name: Upload Test Results
      # actions/upload-artifact@v3.1.1
      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
      with:
        name: test-results
        path: ${{ inputs.test-results-directory }}/test-results-junit.xml
    - name: Upload Test Coverage
      # actions/upload-artifact@v3.1.1
      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
      with:
        name: test-results
        path: ${{ inputs.test-results-directory }}/test-coverage.html
    - name: Publish Test Results
      # EnricoMi/publish-unit-test-result-action@v2.6.0
      uses: EnricoMi/publish-unit-test-result-action@4663c0681217ca1df7425ca7dd9c47ddbdda716e
      if: ${{ github.actor != 'dependabot[bot]' }}
      with:
        files: |
          ${{ inputs.test-results-directory }}/test-results-junit.xml
        check_name: GoLang Tests
        comment_title: GoLang Tests
        compare_to_earlier_commit: false
        action_fail: true
        github_token: ${{ inputs.github-token }}
