name: Build Builder Image
description: Build Builder Image
inputs:
  github-token:
    description: The GitHub token used for accessing internal repositories
    required: true
  builder-dockerfile:
    description: The path to the builder Dockerfile
    required: true
  builder-tag:
    description: The expected builder tag
    required: true
  backends-directory:
    description: The directory to scan for backend apps
    required: true
  image-repository:
    description: The docker repository you are about to push the docker images to
    required: true
  image-version:
    description: The version of the docker images
    required: true
  project-id:
    description: The google cloud project ID
    required: true
  environment:
    description: The environment you are about to deploy to (dev or live)
    required: true
runs:
  using: composite
  steps:
    - name: Builder Builder Image
      run: |
        docker buildx build \
          --build-arg=GITHUB_TOKEN=${{ inputs.github-token }} \
          -f "${{ inputs.builder-dockerfile }}" \
          -t "${{ inputs.builder-tag }}" \
          --load \
          .
      shell: bash
    - name: Builder Builder Image
      run: |
        chimera-build-push-apps.sh ${{ inputs.backends-directory }} ${{ inputs.image-repository }} ${{ inputs.image-version }} ${{ inputs.github-token }}

        chimera-deploy-apps.sh ${{ inputs.backends-directory }} ${{ inputs.image-repository }} ${{ inputs.image-version }} ${{ inputs.project-id }} ${{ inputs.environment }} ${{ inputs.github-token }}
      shell: bash
