name: Chimera test backends
on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true
        description: The working directory where to clone the repo
      bucket-names:
        type: string
        required: true
        description: The GCP buckets that are going to be created
      project-id:
        type: string
        required: true
        description: The default GCP project
    secrets:
      github-token:
        required: true
        description: The GitHub token used for accessing internal repositories
jobs:
  test-apps:
    name: Test apps
    runs-on: self-hosted
    steps:
      - name: ps axu
        run: ps axu