name: Chimera build and deploy backends
on:
  workflow_call:
    inputs:
      builder-dockerfile:
        type: string
        required: true
        description: The path to the builder Dockerfile
      builder-tag:
        type: string
        description: The expected builder tag
        required: true
      source-directories:
        type: string
        required: true
        description: The directories which affect the building process (they are used for sparse checkout)
      backends-directory:
        type: string
        required: true
        description: The directory to scan for backend apps (should be included in source-directories)
      image-repository:
        type: string
        required: true
        description: The docker repository you are about to push the docker images to
      image-version:
        type: string
        required: true
        description: The version of the docker images
      project-id:
        type: string
        required: true
        description: The google cloud project ID
      environment:
        type: string
        required: true
        description: The environment you are about to deploy to (dev or live)
    secrets:
      github-token:
        required: true
        description: The GitHub token used for accessing internal repositories
env:
  CHANGED_DIRECTORIES_FILE: changed-directories
  BUILD_APPS_OUTPUT_FILE: build-apps
  DEPLOY_APPS_OUTPUT_FILE: deploy-apps
jobs:
  build-deploy-apps:
    name: Build and deploy apps
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        # actions/checkout@v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          token: ${{ secrets.github-token }}
          sparse-checkout: ${{ inputs.source-directories }}
      - name: Checkout shared workflows repository
        # actions/checkout@v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          repository: shpeliving/gh-shared-workflows
          token: ${{ secrets.github-token }}
          path: .github/gh-shared-workflows
          # TODO: tag this later
          ref: main
      - name: Get changed directories
        id: changed-files
        # tj-actions/changed-files@v40.1.0
        uses: tj-actions/changed-files@18c8a4ecebe93d32ed8a88e1d0c098f5f68c221b
        with:
          dir_names: true
      - name: Write changed directories to file
        run: echo "${{ steps.changed-files.outputs.all_changed_files }}" > ${CHANGED_DIRECTORIES_FILE}
        shell: bash
      - name: Build builder image
        uses: ./.github/gh-shared-workflows/.github/actions/chimera/build-builder
        with:
          github-token: ${{ secrets.github-token }}
          builder-dockerfile: ${{ inputs.builder-dockerfile }}
          builder-tag: ${{ inputs.builder-tag }}
          changed-directories-file: ${{ env.CHANGED_DIRECTORIES_FILE }}
          build-apps-output-file: ${{ env.BUILD_APPS_OUTPUT_FILE }}
          deploy-apps-output-file: ${{ env.DEPLOY_APPS_OUTPUT_FILE }}
      - name: Build and push apps
        uses: ./.github/gh-shared-workflows/.github/actions/chimera/build-push-apps
        with:
          github-token: ${{ secrets.github-token }}
          build-apps-output-file: ${{ env.BUILD_APPS_OUTPUT_FILE }}
          image-repository: ${{ inputs.image-repository }}
          image-version: ${{ inputs.image-version }}
      - name: Deploy apps
        uses: ./.github/gh-shared-workflows/.github/actions/chimera/deploy-apps
        with:
          github-token: ${{ secrets.github-token }}
          deploy-apps-output-file: ${{ env.DEPLOY_APPS_OUTPUT_FILE }}
          image-repository: ${{ inputs.image-repository }}
          image-version: ${{ inputs.image-version }}
          project-id: ${{ inputs.project-id }}
          environment: ${{ inputs.environment }}
