name: GoLang Continuous Integration and Deployment
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      dockerfile:
        type: string
        required: false
      custom-image-name:
        type: string
        required: false
      values-directory-path:
        type: string
        required: false
      with-tests:
        required: true
        type: string
      push:
        required: true
        type: string
      update-tag:
        required: true
        type: string
      image-version:
        required: true
        type: string
      build-path:
        required: false
        type: string
        default: .
    secrets:
      github-token:
        required: true
jobs:
  golang:
    name: Setup, Build, Test, Publish
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        # actions/checkout@v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          token: ${{ secrets.github-token }}
      - name: Checkout GitHub Shared Repository
        # actions/checkout@v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          repository: shpeliving/gh-shared-workflows
          token: ${{ secrets.github-token }}
          path: .github/gh-shared-workflows
          # TODO: tag this later
          ref: main
      - name: Build Container Image
        uses: ./.github/gh-shared-workflows/.github/actions/docker/build
        id: docker-build
        with:
          environment: ${{ inputs.environment }}
          github-token: ${{ secrets.github-token }}
          with-cache: "false"
          image-version: ${{ inputs.image-version }}
          dockerfile: ${{ inputs.dockerfile }}
          custom-image-name: ${{ inputs.custom-image-name }}
          values-directory-path: ${{ inputs.values-directory-path }}
          build-path: ${{ inputs.build-path }}
      - name: Test Reporter
        uses: ./.github/gh-shared-workflows/.github/actions/golang/test-reporter
        with:
          test-results-directory: ${{ steps.docker-build.outputs.test-results-directory }}
        if: inputs.with-tests == 'true'
      - name: Golang Security Scan
        uses: ./.github/gh-shared-workflows/.github/actions/golang/security-scan
        id: golang-security-scan
        with:
          test-results-directory: ${{ steps.docker-build.outputs.test-results-directory }}
        if: inputs.with-tests == 'true'
      - name: Container Image Vulnerability Scan
        uses: ./.github/gh-shared-workflows/.github/actions/docker/vulnerability-scan
        id: docker-vulnerability-scan
        with:
          image-ref: ${{ steps.docker-build.outputs.image-name }}
        if: inputs.with-tests == 'true'
      - name: Security Review Comment
        uses: ./.github/gh-shared-workflows/.github/actions/comment
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          golang-security-scan: ${{ steps.golang-security-scan.outputs.results }}
          docker-vulnerability-scan: ${{ steps.docker-vulnerability-scan.outputs.results }}
          github-token: ${{ secrets.github-token }}
        if: inputs.with-tests == 'true'
      - name: Push Container Image
        uses: ./.github/gh-shared-workflows/.github/actions/docker/push
        with:
          environment: ${{ inputs.environment }}
          image-ref: ${{ steps.docker-build.outputs.image-name }}
          update-tag: ${{ inputs.update-tag }}
          image-version: ${{ inputs.image-version }}
          values-directory-path: ${{inputs.values-directory-path}}
        if: inputs.push == 'true'
