name: Publish NPM package
on:
  workflow_call:
    inputs:
      package-name:
        type: string
        required: true
        description: The npm package name (the name is automatically prefixed with "@shpeliving/")
      package-directory:
        type: string
        required: false
        default: "."
        description: The directory where the package is located, usually the root of the repository, but in some cases it can be different
      build-directory:
        type: string
        required: true
        description: The directory where the package is built. The parameter is based on the package directory, which default is the root of the repository
      publish-umd:
        type: string
        required: true
        description: If the UMD should be published or not
      publish-umd-folder:
        type: string
        required: false
        default: "false"
        description: If the UMD is folder that should be published or not (ignores publish-umd if true)
      umd-package-root:
        type: string
        required: false
        default: "false"
        description: If we should create an UMD package of root folder or the 'package-directory'
      run-tests:
        type: string
        required: false
        default: "false"
        description: Whether to run tests or not
    secrets:
      node-auth-token:
        required: true
        description: The npm token used for accessing the internal shpeliving repositories
      github-token:
        required: true
        description: The GitHub token used for accessing internal repositories
jobs:
  publish-npm:
    name: Publish NPM package
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        # actions/checkout@v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          token: ${{ secrets.github-token }}
      - name: Install dependencies
        run: |
          cd ${{ inputs.package-directory }}
          npm ci
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.node-auth-token }}
      - name: Run tests
        run: |
          cd ${{ inputs.package-directory }}
          npm run test
        shell: bash
        if: inputs.run-tests == 'true'
      - name: Build package
        run: |
          cd ${{ inputs.package-directory }}
          npm run build:package
        shell: bash
      - name: Get latest package version
        id: latest_version
        run: |
          LATEST_PACKAGE_VERSION=$(npm show @shpeliving/${{ inputs.package-name }} version || true)
          if [ -z "$LATEST_PACKAGE_VERSION" ]; then
            echo "No existing package version found. Defaulting to 0.1.0."
            LATEST_PACKAGE_VERSION="0.1.0"
          else
            echo "Latest version: ${LATEST_PACKAGE_VERSION}"
          fi
          echo "LATEST_VERSION=${LATEST_PACKAGE_VERSION}" >> $GITHUB_ENV
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.node-auth-token }}
      - name: Publish package
        run: |
          cd ${{ inputs.package-directory }}/${{ inputs.build-directory }}

          json_tmp=`cat package.json`
          jq '.name = "@shpeliving/${{ inputs.package-name }}"' <<< $json_tmp > package.json

          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            # split the version string into an array using the "." delimiter
            IFS='.' read -ra VERSION_ARRAY <<< "$LATEST_VERSION"
            # increment the minor version by one
            (( VERSION_ARRAY[1]++ ))
            # set the patch version to 0
            VERSION_ARRAY[2]=0
            echo $VERSION_ARRAY
            # join the version array elements using the "." delimiter
            new_version=$( IFS='.' ; echo "${VERSION_ARRAY[*]:0:3}" )
            echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
            npm version "$new_version" --no-git-tag-version --force --allow-same-version
            npm publish --access public
          else
            branch_name=$(echo ${GITHUB_REF##*/})
            version_suffix="beta-${branch_name}.${GITHUB_RUN_NUMBER}"
            npm version "$LATEST_VERSION" --no-git-tag-version --force --allow-same-version
            published_version=$(npm version prerelease --preid="$version_suffix" --no-git-tag-version --force --allow-same-version)
            echo $published_version
            npm publish --tag beta --access public
            echo "PUBLISHED_VERSION=$published_version" >> $GITHUB_ENV
          fi
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.node-auth-token }}
      - name: Add published version comment
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        # peter-evans/create-or-update-comment@v3.1.0
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Published BETA version
            ### ${{ inputs.package-name }} ${{ env.PUBLISHED_VERSION }}
          edit-mode: replace
      - name: Publish UMD
        run: |
          cd ${{ inputs.package-directory }}
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            if [[ "${{ inputs.umd-package-root }}" == 'true' ]]; then
              npm run build:umd
            fi

            cd ${{ inputs.build-directory }}

            if [[ "${{ inputs.umd-package-root }}" != 'true' ]]; then
              npm run build:umd
            fi

            file_name=./${{ inputs.package-name }}.umd-${NEW_VERSION}.js
            mv ./${{ inputs.package-name }}.umd.js ${file_name}

            # Copy dst to bucket
            gsutil -m cp -r ./${file_name} gs://public-proto-bucket-dev
            gsutil -m cp -r ./${file_name} gs://public-proto-bucket-prod
          else
            echo "NONE"
          fi
        shell: bash
        if: inputs.publish-umd == 'true' && inputs.publish-umd-folder == 'false'
      - name: Publish UMD Folder
        run: |
          cd ${{ inputs.package-directory }}
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            if [[ "${{ inputs.umd-package-root }}" == 'true' ]]; then
              npm run build:umd
            fi

            cd ${{ inputs.build-directory }}

            if [[ "${{ inputs.umd-package-root }}" != 'true' ]]; then
              npm run build:umd
            fi

            build_dir=./umd

            # Copy dst to bucket
            gsutil -m cp -r ${build_dir}/* gs://public-proto-bucket-dev/${{ inputs.package-name }}/${NEW_VERSION}
            gsutil -m cp -r ${build_dir}/* gs://public-proto-bucket-prod/${{ inputs.package-name }}/${NEW_VERSION}
          else
            echo "NONE"
          fi
        shell: bash
        if: inputs.publish-umd-folder == 'true'
